version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - SECRET_KEY=63f76032421b8be2f858c87344eb01bfcf05fd3953fca613aad8d169b53fd405